### ISSUE TITLE
Data Request : New Zealand Lockdown Policies

### ISSUE THREAD

**Issue by whymath** [Auquan/help_project#10]
# Data Request Details
#### Team Name : 
Team 2

#### Data Source Website : 
_PDFs_
https://covid19.govt.nz/assets/resources/tables/COVID-19-alert-levels-summary.pdf
https://covid19.govt.nz/assets/resources/tables/COVID-19-alert-levels-detailed.pdf
https://covid19.govt.nz/assets/resources/legislation-and-key-documents/COVID-19-national-action-plan-2-issued-1-April.pdf
https://covid19.govt.nz/assets/resources/legislation-and-key-documents/COVID19-National-Action-Plan-3-as-of-22-April-extended.pdf

_HTMLs_
https://covid19.govt.nz/latest-updates/alert-level-2-changes-confirmed-for-friday-29-may/
https://covid19.govt.nz/latest-updates/alert-level-1-measures/

_Scraping_
https://covid19.govt.nz/latest-updates/

#### Output Format : 
csv

#### Input Format (based on Data Source): 
PDF
HTML

#### Date Needed By : 
05/06/2020

#### Additional Comments : 
Output Drive folder - https://drive.google.com/drive/u/0/folders/1nSt6RaoNggyiXHxtWSk9zzhHyQjNdo_L

For scraping, need to traverse through query results displayed on the page, and generate a list of hyperlinks whose displayed text has the words "alert level" (case-insensitive)

**Comment by salil-gtm** [comment]
- [ ] PDFs
- [ ] HTML
- [ ] Scraping

**Comment by salil-gtm** [comment]
All requests submitted as Txt files in the mentioned Drive Link
