### ISSUE TITLE
Data Request : India Lockdown Policies

### ISSUE THREAD

**Issue by whymath** [Auquan/help_project#9]
# Data Request Details

#### Team Name : 
Team 2

#### Data Source Website : 
https://www.mha.gov.in/sites/default/files/Guidelines_0.pdf
https://www.mha.gov.in/sites/default/files/MHA%20order%20dt%2015.04.2020%2C%20with%20Revised%20Consolidated%20Guidelines_compressed%20%283%29.pdf
https://www.mha.gov.in/sites/default/files/MHA%20Order%20Dt.%201.5.2020%20to%20extend%20Lockdown%20period%20for%202%20weeks%20w.e.f.%204.5.2020%20with%20new%20guidelines.pdf
https://mha.gov.in/sites/default/files/MHAOrderextension_1752020_0.pdf
https://www.mha.gov.in/sites/default/files/MHAOrderDt_30052020.pdf

#### Output Format : 
csv

#### Input Format (based on Data Source): 
PDF

#### Date Needed By : 
04/06/2020

#### Additional Comments : 
Output Drive folder - https://drive.google.com/drive/u/0/folders/1QLBj92WzyBhZg17vUqOGKd9-dc29y6V2

**Comment by salil-gtm** [comment]
Txt files submitted in the mentioned Drive Link.
